services:
  fe:
    build:
      context: ./fe_repo/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    container_name: vite-frontend
    restart: unless-stopped
  # be: # Add your be image here
