name: Bug report
description: File a report for a bug in the project
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: input
    id: reproduction_steps
    attributes:
      label: "Steps to reproduce"
      description: "Please provide the steps to reproduce this issue."
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. See error"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What should happen?"
    validations:
      required: true
  - type: textarea
    id: observed
    attributes:
      label: "Observed behavior"
      description: "What actually happens?"
    validations:
      required: true
