name: CI for E2E

on:
  push:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    services:
      frontend:
        image: node:18
        options: --network-alias frontend
        env:
          PORT: 3000
        volumes:
          - ./fe_repo:/app
        working_dir: /app
        command: >
          sh -c "npm install -g pnpm && pnpm install && pnpm build && pnpm start"


      backend:
        image: python:3.10
        options: --network-alias backend
        env:
          PORT: 5000
        volumes:
          - ./be_repo:/app
        working_dir: /app
        command: >
          sh -c "pip install -r requirements.txt && python app.py"

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"


      # Step 3: 等待前后端服务启动
      - name: Wait for services to be ready
        run: |
          # 等待前端服务
          until curl -s http://frontend:3000; do
            echo "Waiting for frontend to be ready..."
            sleep 5
          done

          # 等待后端服务
          until curl -s http://backend:5000; do
            echo "Waiting for backend to be ready..."
            sleep 5
          done

      # Step 5: 运行E2E测试
      - name: Run E2E tests
        run: |
          python test_e2e.py
